services:
  postgres:
    image: postgres:latest
    container_name: postgres_corewebkit
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ecotel@2025
      POSTGRES_DB: corewebkit
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-net

volumes:
  postgres_data:

networks:
  backend-net:
    external: true
